### ISSUE TITLE
Remove the need for hard-coded /home URL and user.home endpoint

### ISSUE THREAD

**Issue by wolfv** [lingthio/Flask-User#70] opened 2015-04-27 13:40 UTC
In my opinion, the /home route should be configurable and not hard-coded:

https://github.com/lingthio/Flask-User/blob/master/flask_user/__init__.py#L194

also, i think it would be better as /user/home

Wolf

**Comment by bobwaycott** [comment] 2015-05-05 13:46
I totally agree. Just upgraded a client project to latest Flask-User and wound up getting bit by this. It's pretty unfriendly to force non-customizable URLs into an application, because most apps probably know exactly where they want a logged-in user to wind up.

**Comment by lingthio** [comment] 2015-07-13 02:56
Hi @wolfv 
Thanks for entering this issue! Wow, I have no idea where that hard-coded user.home endpoint came from. It's used when inactive users and users with an unconfirmed email address try to log in. When this happens we can:

a) redirect them to the login page showing the flash message
b) redirect them to a user-configurable home page

I'm leaning towards implementing a)

**Comment by lingthio** [comment] 2015-07-13 02:58
@bobwaycott,
Thanks for your feedback! It's not easy to write a fully customizable package while keeping it simple, but I think it can be achieved, so I really appreciate your suggestions.
I'll think about this some more and will let you know what I came up with.

**Comment by lingthio** [comment] 2015-07-13 05:57
Fixed in v0.6.3.

**Closed by lingthio** 2015-07-13 05:57 UTC
Labels: bug, Dev completed, Released

**Comment by wolfv** [comment] 2015-07-13 10:24
Hi Ling, thanks for fixing this!
